database:
  database: albireo
  username: postgres
  password: 123456
  host: 127.0.0.1
  port: 5432

deluge:
  host: 127.0.0.1
  port: 58846
  username: ''
  password: deluge

task:
  interval: 15  # unit minute
  info_scanner:
    scan_time: # A info scanner will scheduled for once a day at this particular time. it is not an accurate time, default is 23:00
    scan_time_format: # default is '%H:%M' see https://docs.python.org/2/library/datetime.html#strftime-strptime-behavior
  delete_delay: # delay for delete any resources. 0 represents immediately
    bangumi: 10 # unit minute
    episode: 0 # unit minute

download:
  location: /  # change this location

app_secret_key: amanogawa_saya

feedparser:
  timeout: 60 # timeout in seconds
  proxy:
    default: # default http proxy for feedparser , for example http://127.0.0.1:8000
#    dmhy: # proxy for dmhy, either an url string or a dictionary with http, https, ftp scheme
#      http: http://127.0.0.1:8000/
#      https: https://127.0.0.1:9000/
#      ftp: http://127.0.0.1:8000/

# Setting a different domain for resource will speed up your page load
# a scheme is required, e.g. https://static.example.com
# this is optional
domain:
  image: # the image domain for your image resource, such as thumbnails and cover
  video: # the video domain for your video resource
